require "a-millert.set"
require "a-millert.remap"
require "a-millert.plugins"
require "a-millert.cmp"
require "a-millert.lsp"
require "a-millert.telescope"
require "a-millert.gitsigns"
require "a-millert.treesitter"
require "a-millert.nvim-tree"
require "a-millert.bufferline"
require "a-millert.lualine"
require "a-millert.project"
-- require "a-millert.impatient"
-- require "a-millert.indentline"
-- require "a-millert.alpha"
require "a-millert.whichkey"
-- require "a-millert.autocommands"
